### ISSUE TITLE
jamf disable movements of the AirPlay box

### ISSUE THREAD

**Issue by nebi52** [NU-ITS/mdm-image-viewer#4]
Hi guys, is it possible to disable the movements of the airplay box in jamf?
actually my jamf setup looks like https://imgur.com/smaqiXK
thank you and best regards from germany

**Comment by doschupp** [comment]
Hi, at the moment it's not possible, but it's not very difficult to implement. I will open a new PR for this feature. 
But.. it looks like the application is not really being developed any more.. Because of another feature we decided to distribute an adapted version as an in-house application via Jamf.

Best regards from Bavaria;)

**Comment by qharouff** [comment]
Thanks @doschupp, I haven't been able to do a lot with this app in the last year but these are important changes and I have a few other things I need to add. I will try to get these committed and implemented into the App Store soon.

**Comment by doschupp** [comment]
Hi @qharouff, thanks for the information. If you need any help let is know. We (mac team @ university erlangen) can support you.

**Comment by qharouff** [comment]
Added several options for this in version 1.0.4 (see README page for more details)
- edu.nebraska.ImageViewer.airplayViewMovement: Set to "Inactive" to disable movement of the airplay box.
- edu.nebraska.ImageViewer.airplayViewPositionX: Set the X coordinate of the Airplay box.
- edu.nebraska.ImageViewer.airplayViewPositionX: Set the Y coordinate of the Airplay box.

Features have been added in and uploaded to the App Store. Currently pending App Store review.
